name: AutoDeployDevelop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Install requirements
      run: |
        apt update
        apt install -y build-essential dnsutils wget git curl tree
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
