name: AutoDeployDevelop

on: 
  push:
    branches: 
      - develop

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
    - name: deploy
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        sudo apt update
        sudo apt install -y build-essential dnsutils wget git curl tree
        sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
        sudo chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        echo "Putting kubecfg in /tmp/config:"
        echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/config
        echo "Contents of /tmp/config:"
        kubectl --kubeconfig /tmp/config rollout restart -n swabweb-test deployment nginx
